name: staging deploy
on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed  
  workflow_dispatch:

jobs:
    stage_deploy:
      if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}   
      name: Stage deploy
      runs-on: ubuntu-latest
      steps:
      - name: git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGEHOST }}
          username: mb
          passphrase: ${{ secrets.STAGEDEPLPASS }}
          key: ${{ secrets.STAGEDEPLKEY }}
          script: |
              cd ${{ secrets.APPDIR }}
              git pull    

      - name: npm install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGEHOST }}
          username: mb
          passphrase: ${{ secrets.STAGEDEPLPASS }}
          key: ${{ secrets.STAGEDEPLKEY }}
          script: docker-compose -f /var/maxibooking/d8b-front-npm-cli.yml run --rm d8b-front-npm-cli npm install
                                  
      - name: front build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGEHOST }}
          username: mb
          passphrase: ${{ secrets.STAGEDEPLPASS }}
          key: ${{ secrets.STAGEDEPLKEY }}
          script: docker-compose -f /var/maxibooking/d8b-front-npm-cli.yml run --rm d8b-front-npm-cli node_modules/.bin/ng build --prod

      - name: nginx restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGEHOST }}
          username: mb
          passphrase: ${{ secrets.STAGEDEPLPASS }}
          key: ${{ secrets.STAGEDEPLKEY }}
          script: docker container restart mb-nginx

      - name: Send email for successfull tests
        uses: dawidd6/action-send-mail@v2
        if: ${{ success() }}
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Success - the staging deploy of frontend - ${{github.repository}}
          body: The staging deploy of frontend -${{github.repository}}-  have been completed successfully
          to: ${{secrets.SUCCESS_MAIL_RECEPIENTS}}
          from: Github actions
          # Optional content type (defaults to text/plain):
          content_type: text/html

    skip_email:
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}   
      name: Send email if the tests are failure and the staging deploy have been skipped
      runs-on: ubuntu-latest
      steps:
      - name: Send email if the test are failure and the staging deploy have been skipped
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Skip - the staging deploy of frontend - ${{github.repository}}
          body: The tests are failure and the staging deploy have been skipped - ${{github.repository}}
          to: ${{secrets.FAIL_MAIL_RECEPIENTS}}
          from: Github actions
          # Optional content type (defaults to text/plain):
          content_type: text/html
